### ISSUE TITLE
(node:7048) UnhandledPromiseRejectionWarning: Error: Parameter 'toolPath' cannot be null or empty.

### ISSUE THREAD

**Issue by wabJMS** [PowerON-UK/AKV-Code-Sign#2]
Started receiving the following error:

(node:13640) UnhandledPromiseRejectionWarning: Error: Parameter 'toolPath' cannot be null or empty.
    at new ToolRunner (E:\azagent\A1\_work\_tasks\AKV-Code-Sign_02dbaba0-04f3-4c6e-a780-d0c4d36a7f8c\1.0.3\node_modules\azure-pipelines-task-lib\toolrunner.js:29:19)
    at Object.tool (E:\azagent\A1\_work\_tasks\AKV-Code-Sign_02dbaba0-04f3-4c6e-a780-d0c4d36a7f8c\1.0.3\node_modules\azure-pipelines-task-lib\task.js:1282:14)
    at E:\azagent\A1\_work\_tasks\AKV-Code-Sign_02dbaba0-04f3-4c6e-a780-d0c4d36a7f8c\1.0.3\taskRun.js:68:32
    at Generator.next (<anonymous>)
    at E:\azagent\A1\_work\_tasks\AKV-Code-Sign_02dbaba0-04f3-4c6e-a780-d0c4d36a7f8c\1.0.3\taskRun.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\azagent\A1\_work\_tasks\AKV-Code-Sign_02dbaba0-04f3-4c6e-a780-d0c4d36a7f8c\1.0.3\taskRun.js:4:12)
    at signFiles (E:\azagent\A1\_work\_tasks\AKV-Code-Sign_02dbaba0-04f3-4c6e-a780-d0c4d36a7f8c\1.0.3\taskRun.js:66:12)
    at E:\azagent\A1\_work\_tasks\AKV-Code-Sign_02dbaba0-04f3-4c6e-a780-d0c4d36a7f8c\1.0.3\taskRun.js:40:13
    at Generator.next (<anonymous>)
(node:13640) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13640) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ld0614** [comment]
Hi @wabJMS sorry for the delay in responding, we're not seeing this issue on our hosted runners. Could you provide the following information for me please?

- Is this a hosted or dedicated runner?
- What OS/SKU is the runner using
- What are the parameters that you have configured on the task?

Thanks
